version:  '3.3'

services:
  mongodb:
    build: ./mongodb
    ports:
    - 27017:27017
    restart: on-failure
    environment:
    - MONGO_INITDB_DATABASE=find_my_cve
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - ./mongodb/backups:/backups
    - ./mongodb/script:/script
    - ./mongodb/bdd:/data/db

    networks: 
    - backend

networks: 
  backend:
