version:  '3.3'

services:
  mongodb:
    build: ./mongodb
    container_name: mongodb
    ports:
    - 27017:27017
    restart: on-failure
    environment:
    - MONGO_INITDB_DATABASE=find_my_cvf
    - MONGO_INITDB_ROOT_USERNAME=root
    - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
    - ./mongodb/backups:/backups
    - ./mongodb/script:/script
    - ./mongodb/bdd:/data/db

    networks: 
    - backend
  
  web:
    build: ./flask
    container_name: flask
    ports:
      - "80:5000"
    volumes:
      - ./flask:/app
    networks:
      - backend

networks: 
  backend: